#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.3 effective-5.10 (swiftlang-6.3.3.1.3 clang-2100.1.1.101)
#ifndef CASTLESDK_SWIFT_H
#define CASTLESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CastleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CastleSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class CastleConfiguration;
@class NSString;
@class NSURL;
/// The Castle iOS SDK entry point.
/// All methods are static. Configure the SDK once at app launch, then use the tracking
/// and token methods throughout your app.
/// \code
/// try Castle.configure(CastleConfiguration(publishableKey: "pk_..."))
/// Castle.userJwt("eyJ...")
/// Castle.custom(name: "checkout_started")
///
/// \endcode
SWIFT_CLASS_NAMED("Castle")
@interface Castle : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Configures the Castle SDK with the provided configuration.
/// Must be called on the <em>main thread</em>, typically in
/// <code>application(_:didFinishLaunchingWithOptions:)</code>.
/// Throws <code>CastleConfigurationError</code> if the publishable key is invalid or the call
/// is made off the main thread.
/// \param configuration A <code>CastleConfiguration</code> instance with your
/// Publishable Key and any custom settings.
///
///
/// throws:
/// <code>CastleConfigurationError/invalidPublishableKey</code> or
/// <code>CastleConfigurationError/mustConfigureOnMainThread</code>
+ (BOOL)configure:(CastleConfiguration * _Nonnull)configuration error:(NSError * _Nullable * _Nullable)error;
/// Configures the Castle SDK with a Publishable Key using default settings.
/// Convenience overload of <code>configure(_:)</code>. Must be called on the <em>main thread</em>.
/// \param publishableKey Your Castle Publishable Key (<code>pk_...</code>).
///
///
/// throws:
/// <code>CastleConfigurationError/invalidPublishableKey</code> or
/// <code>CastleConfigurationError/mustConfigureOnMainThread</code>
+ (BOOL)configureWithPublishableKey:(NSString * _Nonnull)publishableKey error:(NSError * _Nullable * _Nullable)error;
/// Configures the Castle SDK asynchronously.
/// Dispatches configuration to the main thread internally, so it is safe to call from
/// any thread or <code>Task</code>.
/// Prefer this overload when calling from an async context.
/// \param configuration A <code>CastleConfiguration</code> instance with your
/// Publishable Key and any custom settings.
///
///
/// throws:
/// <code>CastleConfigurationError/invalidPublishableKey</code>
+ (void)configureAsync:(CastleConfiguration * _Nonnull)configuration completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler;
/// Resets the SDK to an unconfigured state, clearing all internal state and flushing
/// any pending events.
/// Call this if you need to reconfigure the SDK, for example when switching
/// environments.
+ (void)resetConfiguration;
/// Tracks a custom event with the given name.
/// Requires a user JWT to be set via <code>userJwt(_:)</code>. Events are queued and flushed
/// automatically.
/// \param name The name of the event (e.g. <code>"checkout_started"</code>). Must not be
/// empty.
///
+ (void)customWithName:(NSString * _Nonnull)name;
/// Tracks a custom event with the given name and properties.
/// Requires a user JWT to be set via <code>userJwt(_:)</code>. Events are queued and flushed
/// automatically.
/// \param name The name of the event (e.g. <code>"checkout_started"</code>). Must not be empty.
///
/// \param properties Optional key-value metadata attached to the event.
///
+ (void)customWithName:(NSString * _Nonnull)name properties:(NSDictionary<NSString *, id> * _Nonnull)properties;
/// Tracks a screen view event.
/// Requires a user JWT to be set via <code>userJwt(_:)</code>. Events are queued and flushed
/// automatically.
/// \param name The screen name (e.g. <code>"Checkout"</code>). Must not be empty.
///
+ (void)screenWithName:(NSString * _Nonnull)name;
/// Sets the signed user JWT, binding subsequent events and tokens to the identified
/// user.
/// Call this after login, or at app launch if the user is already authenticated.
/// Events will not be queued until a JWT is set.
/// \param userJwt A signed JWT generated by your backend representing the
/// current user.
///
+ (void)setUserJwt:(NSString * _Nullable)userJwt;
/// Flushes all queued events to the Castle backend immediately.
/// The SDK flushes automatically when the queue reaches <code>flushLimit</code>. Call this
/// manually
/// when you want to ensure events are delivered at a specific point, such as before
/// logout.
+ (void)flush;
/// :nodoc:
+ (void)flushIfNeeded:(NSURL * _Nonnull)url;
/// Flushes pending events and clears the current user JWT.
/// This flushes any pending events and clears the stored user JWT.
/// Call this on logout to disassociate the device from the current user.
+ (void)reset;
/// The HTTP header name used to pass the Castle request token to your backend.
/// Value: <code>X-Castle-Request-Token</code>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull requestTokenHeaderName;)
+ (NSString * _Nonnull)requestTokenHeaderName SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
+ (NSString * _Nonnull)versionString SWIFT_WARN_UNUSED_RESULT;
/// Creates a request token representing the current device state.
/// Tokens expire after 120 seconds and should be passed to your backend as the
/// <code>X-Castle-Request-Token</code> header on each request. This method is synchronous and
/// thread-safe — it can be called from any thread.
/// Can be called as soon as <code>configure(_:)</code> returns. Tokens created that early are
/// valid but carry less sensor data, waiting ~1s is recommended
///
/// returns:
/// A base64-encoded token string. <code>nil</code> if the SDK is not configured, or
/// if the device identifier is unavailable
+ (NSString * _Nullable)createRequestToken SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
+ (NSURL * _Nonnull)baseURL SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
+ (BOOL)isAllowlistURL:(NSURL * _Nullable)url SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
+ (NSString * _Nullable)publishableKey SWIFT_WARN_UNUSED_RESULT;
/// :nodoc:
+ (NSString * _Nullable)userJwt SWIFT_WARN_UNUSED_RESULT;
@end

/// Configuration object passed to <code>Castle.configure</code> or <code>Castle.configureAsync</code>.
/// Create an instance with your Publishable Key and adjust any optional settings before
/// passing it to <code>Castle.configure</code>.
/// \code
/// let configuration = CastleConfiguration(publishableKey: "pk_...")
/// configuration.isDebugLoggingEnabled = true
/// try Castle.configure(configuration)
///
/// \endcode
SWIFT_CLASS("_TtC9CastleSDK19CastleConfiguration")
@interface CastleConfiguration : NSObject
/// Your Castle Publishable Key. Found in the <a href="https://dashboard.castle.io/settings">Castle
/// Dashboard</a>.
/// Must start with <code>pk_</code> and be 35 characters long.
@property (nonatomic, readonly, copy) NSString * _Nonnull publishableKey;
/// Automatically track screen views by hooking into <code>UIViewController</code> lifecycle
/// events. Default: <code>false</code>.
/// When enabled, a <code>screen</code> event is sent each time a <code>UIViewController</code> appears on
/// screen.
/// For manual tracking use <code>Castle.screen(name:)</code> instead.
@property (nonatomic) BOOL screenTrackingEnabled;
/// Enable verbose logging to the console. Default: <code>false</code>.
/// Set to <code>true</code> during development to inspect SDK behaviour. Disable for production
/// builds.
@property (nonatomic) BOOL debugLoggingEnabled;
/// Collect touch interaction signals for request tokens. Default: <code>true</code>.
/// Set to <code>false</code> to disable touch event collection.
@property (nonatomic) BOOL touchCollectionEnabled;
/// Automatically inject the Castle request token into outgoing <code>URLSession</code> requests
/// whose host matches an entry in <code>baseURLAllowList</code>. Default: <code>false</code>.
/// The token is added as the <code>X-Castle-Request-Token</code> header. Requires
/// <code>baseURLAllowList</code> to be set.
@property (nonatomic) BOOL tokenAutoForwardingEnabled;
/// Maximum number of events held in the local queue before older events are dropped.
/// Default: <code>1000</code>.
@property (nonatomic) NSInteger maxQueueLimit;
/// Number of queued events that triggers an automatic flush to the Castle backend.
/// Default: <code>20</code>.
@property (nonatomic) NSInteger flushLimit;
/// Closure that returns the IDFA (Identifier for Advertisers) as a <code>String</code>.
/// Used together with <code>isAdvertisingTrackingEnabled</code> to include the advertising
/// identifier in signals.
/// Requires the App Tracking Transparency permission granted by the user
/// (<code>ATTrackingManager.requestTrackingAuthorization</code>).
/// Leave <code>nil</code> if your app does not use advertising tracking.
@property (nonatomic, copy) NSString * _Nonnull (^ _Nullable adSupportBlock)(void);
/// Include the advertising identifier (IDFA) in collected signals. Default: <code>true</code>.
/// Only has an effect when <code>adSupportBlock</code> is also set. Set to <code>false</code> to exclude
/// the IDFA
/// regardless of whether a block is provided.
@property (nonatomic) BOOL enableAdvertisingTracking;
/// Automatically track application lifecycle events as custom Castle events. Default:
/// <code>true</code>.
/// When enabled, the following events are tracked automatically:
/// <ul>
///   <li>
///     <code>Application Did Become Active</code>
///   </li>
///   <li>
///     <code>Application Did Enter Background</code>
///   </li>
///   <li>
///     <code>Application Will Terminate</code>
///   </li>
/// </ul>
@property (nonatomic) BOOL enableApplicationLifecycleTracking;
/// List of base URLs for automatic token forwarding.
/// Only the scheme and host of each URL are used — any path or query components are
/// ignored.
/// Required when <code>isTokenAutoForwardingEnabled</code> is <code>true</code>.
/// \code
/// configuration.baseURLAllowList = [URL(string: "https://api.yourapp.com")!]
///
/// \endcode
@property (nonatomic, copy) NSArray<NSURL *> * _Nullable baseURLAllowList;
/// :nodoc:
@property (nonatomic, readonly, copy) NSURL * _Nonnull baseURL;
/// Creates a configuration with the given Publishable Key and default settings.
/// \param publishableKey Your Castle Publishable Key (<code>pk_...</code>).
///
- (nonnull instancetype)initWithPublishableKey:(NSString * _Nonnull)publishableKey OBJC_DESIGNATED_INITIALIZER;
/// Creates a configuration with the given Publishable Key. Objective-C convenience
/// factory method.
/// \param publishableKey Your Castle Publishable Key (<code>pk_...</code>).
///
///
/// returns:
/// A new <code>CastleConfiguration</code> instance with default settings.
+ (CastleConfiguration * _Nonnull)configurationWithPublishableKey:(NSString * _Nonnull)publishableKey SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Errors thrown by <code>Castle.configure</code> and <code>Castle.configureAsync</code>.
typedef SWIFT_ENUM(NSInteger, CastleConfigurationError, open) {
/// The publishable key is missing, empty, or does not match the expected format
/// (<code>pk_</code> prefix, 35 characters).
  CastleConfigurationErrorInvalidPublishableKey = 0,
/// <code>Castle.configure</code> (sync) was called from a background thread. It must be called
/// on the main thread.
  CastleConfigurationErrorMustConfigureOnMainThread = 1,
};
static NSString * _Nonnull const CastleConfigurationErrorDomain = @"CastleSDK.CastleConfigurationError";

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
